name: loan2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  image_picker: ^1.1.1
  connectivity_plus: ^6.0.0
  
  # Dependencies for Encryption
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  
  # Dependencies for Movement Screen & other features
  camera: ^0.10.5
  sensors_plus: ^5.0.1
  permission_handler: ^11.0.1
  flutter_tts: ^3.8.3
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  fl_chart: ^0.66.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
